---
name: ci

on: [pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: guides
          persist-credentials: false

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ruby/rubygems
          path: rubygems
          ref: "4.0"
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: 4.0
          bundler-cache: true
          working-directory: guides

      - name: Build jekyll
        run: bundle exec jekyll build
        working-directory: guides

      - name: Generate command guide
        run: RUBYOPT="--disable-gems -I../rubygems/lib" RUBYGEMS_DIR="../rubygems" bundle exec rake command_guide && git diff --exit-code
        working-directory: guides

      - name: Lint generated markdown
        run: bundle exec mdl --rules MD009,MD012 command-reference.md
        working-directory: guides
